name: build
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  build:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v4
      with:
          submodules: recursive
          lfs: true

    - name: setup toolchain
      run: |
        cd toolchain
        tar xzf riscv32-embecosm-ubuntu2204-gcc13.2.0.tar.gz

    - name: build
      run: |
        RISCV_TOOLCHAIN=$PWD/toolchain/riscv32-embecosm-ubuntu2204-gcc13.2.0 make
