name: build
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  build:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: setup toolchain
      run: |
        mkdir toolchain
        cd toolchain
        wget https://github.com/MichaelBell/riscv-gnu-toolchain/releases/download/13.2.0-tqv-1.0/riscv32ec-13.2.0-tqv-1.0.tar.gz
        tar xzf riscv32ec*.tar.gz

    - name: build
      run: |
        RISCV_TOOLCHAIN=$PWD/toolchain/riscv make
        cd pngdec
        RISCV_TOOLCHAIN=$PWD/../toolchain/riscv make

    - name: upload libs
      uses: actions/upload-artifact@v4
      with:
        name: tinyQV-sdk
        path: |
          tinyQV.a
          tinyQV-sd.a
          pngdec/tinyQV-pngdec.a
