name: build
on: [ push, workflow_dispatch, pull_request ]
jobs:
  build:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: setup toolchain
      run: |
        mkdir toolchain
        cd toolchain
        wget https://github.com/MichaelBell/riscv-gnu-toolchain/releases/download/16.1.0-tqv-2.1/riscv32ec-16.1.0-tqv-2.1.tar.gz
        tar xzf riscv32ec*.tar.gz

    - name: build
      run: |
        RISCV_TOOLCHAIN=$PWD/toolchain/tinyQV make
        RISCV_TOOLCHAIN=$PWD/toolchain/tinyQV make tinyQV-sd.a
        cd pngdec
        RISCV_TOOLCHAIN=$PWD/../toolchain/tinyQV make

    - name: upload libs
      uses: actions/upload-artifact@v4
      with:
        name: tinyQV-sdk
        path: |
          tinyQV.a
          tinyQV-asteroids.a
          tinyQV-sd.a
          pngdec/tinyQV-pngdec.a
